# Generated by Django 5.2 on 2025-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('search_name', models.CharField(db_index=True, default=None, editable=False, max_length=200)),
                ('csfd_hash', models.CharField(default=None, editable=False, max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('search_name', models.CharField(db_index=True, default=None, editable=False, max_length=200)),
                ('csfd_hash', models.CharField(default=None, editable=False, max_length=32, unique=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='movies.actor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
